# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Check that all mandatory variables are defined.
  assert:
    that:
      - interface is defined
      - unicast_peers is defined
      - virtual_ip_address is defined
      - virtual_ipaddress_config is defined
      - state is defined
      - priority is defined
      - weight is defined
      - virtual_router_id is defined
    fail_msg: "Some mandatory variables are not set."
    success_msg: "All mandatory variables are set."

- name: Install dependencies for Keepalived.
  become: yes
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ keepalived_dependencies }}"

- name: Create Keepalived Group.
  become: yes
  group:
    name: "{{ keepalived_group }}"
    system: yes
    state: present

- name: Add Keepalived System User.
  become: yes
  user:
    name: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    system: yes
    create_home: no

- name: Check whether Keepalived binary is installed.
  stat:
    path: "{{ keepalived_path }}"
  register: keepalived_installed

- name: Get Keepalived version.
  command:
    cmd: "{{ keepalived_path }} --version"
  register: keepalived_version_installed
  when: keepalived_installed.stat.exists
  # Version string will always result in state "changed".
  changed_when:
    - keepalived_version_installed.rc != 0
    - keepalived_version_installed.stdout | regex_search('^Keepalived v=[0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{1,2}') != 'Keepalived v='+keepalived_version

- name: Put value of installed version into an Ansible fact.
  set_fact:
    installed_keepalived_version: "{{ keepalived_version_installed.stderr | regex_search('^Keepalived v[0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{1,2}') }}"
  when: keepalived_installed.stat.exists

- name: Cut off all unwanted characters from the version string.
  set_fact:
    reduced_installed_keepalived_version: "{{ installed_keepalived_version[12:] }}"
  when: installed_keepalived_version is defined

- name: Output version strings of installed and to be installed Keepalived.
  debug:
    msg: "Installed version: {{ reduced_installed_keepalived_version }}, version to be installed: {{ keepalived_version }}."
  when: installed_keepalived_version is defined

- name: Check if both version strings are equal.
  set_fact:
    is_keepalived_version_equal: "{{ reduced_installed_keepalived_version is version(keepalived_version, operator='==', strict=True) }}"
  when: keepalived_installed.stat.exists

- name: Continue with installing Keepalived if Keepalived is not already installed or versions are not equal.
  when: not keepalived_installed.stat.exists or (keepalived_installed.stat.exists and not (is_keepalived_version_equal|bool))
  block:

    - name: Download and extract keepalived-{{ keepalived_version }}.tar.gz into {{ keepalived_base_dir }}.
      become: yes
      unarchive:
        src: "{{ keepalived_download_url }}"
        dest: "{{ keepalived_base_dir }}"
        remote_src: yes
        owner: "{{ keepalived_user }}"
        group: "{{ keepalived_group }}"
        mode: '0755'

    - name: Configure Keepalived to be build.
      become: yes
      command: "./configure --prefix={{ keepalived_build_dir_path }}"
      args:
        chdir: "{{ keepalived_build_dir_path }}"

    - name: Build Keepalived from source.
      become: yes
      make:
        chdir: "{{ keepalived_build_dir_path }}"

    - name: Install Keepalived binaries.
      become: yes
      make:
        chdir: "{{ keepalived_build_dir_path }}"
        target: install

- name: Create Keepalived Configuration Directory.
  become: yes
  file:
    path: "{{ keepalived_conf_dir }}"
    state: directory
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: '0755'

- name: Create Configuration File.
  become: yes
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_conf_file_path }}"
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: '0644'

- name: Copy Keepalived Service File.
  become: yes
  copy:
    src: "{{ keepalived_service_template_file_path }}"
    dest: "{{ keepalived_service_file_path }}"
    remote_src: yes
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_group }}"
    mode: '0644'

- name: Register Keepalived Systemd Service.
  become: yes
  service:
    name: "{{ keepalived_name }}"
    state: started
    enabled: yes
  when: not keepalived_installed.stat.exists

...
