# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# Play to create and provision instance.
- name: Converge
  hosts: all
  tasks:
    - name: "Include keepalived_role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    router_id: 'KEEPALIVED_1'
    interface: "enp0s8"
    state: 'MASTER'
    priority: '200'
    weight: '2'
    virtual_router_id: '123'
    unicast_src_ip: '192.168.33.14'
    unicast_peers:
      - '192.168.33.15'
      - '192.168.33.16'
    virtual_ip_address: "192.168.33.100"
    virtual_ipaddress_config: "192.168.33.100 dev enp0s8"

...
